---
- hosts: all
  sudo: yes
  user: ubuntu
  tasks:
#    - name: Download zsh installer
 #     get_url:
  #      url: https://olo-chef-bucket.s3.ap-south-1.amazonaws.com/ossec-agent/atomic
   #     dest: /tmp/atomic
    #    mode: 0755

#    - name: install atomic
#      shell: /tmp/atomic
#    - name: move
#      shell: mv /var/ossec/etc_old /var/ossec/etc
  #  - name: instaall ossec
   #   apt:
   #     name: ossec-hids-agent
   #     state: present
    - name:
      get_url:
        url: https://olo-chef-bucket.s3.ap-south-1.amazonaws.com/ossec-agent/ossec-agent.conf
        dest: /var/ossec/etc/ossec.conf
    - name: register to ossec server
      shell: /var/ossec/bin/agent-auth -m 10.3.11.104 -A $HOSTNAME -p 1515
    - name: restart ossec
      service:
        name: ossec
        state: restarted
      
